using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using QuestPDF.Infrastructure;
using ResumeService.Common;
using ResumeService.Data;
using ResumeService.Middleware;
using ResumeService.Repositories;
using ResumeService.Repositories.Interfaces;
using ResumeService.Services;
using Serilog;
using MassTransit;
using ResumeService.Consumers;
using System.Net.Http.Json;
using System.Security.Cryptography;

// ── QuestPDF license — must be set BEFORE any QuestPDF type is first accessed ──
QuestPDF.Settings.License = LicenseType.Community;

var builder = WebApplication.CreateBuilder(args);

builder.Host.UseSerilog((ctx, cfg) =>
{
    cfg.ReadFrom.Configuration(ctx.Configuration)
       .Enrich.FromLogContext()
       .WriteTo.Console(new Serilog.Formatting.Compact.CompactJsonFormatter())
       .WriteTo.File(new Serilog.Formatting.Compact.CompactJsonFormatter(),
           path: "logs/resume-.log",
           rollingInterval: RollingInterval.Day);
});

builder.Services.AddControllers()
    .AddJsonOptions(opts =>
    {
        // Prevent circular reference crash (Resume → Education → Resume → ...)
        opts.JsonSerializerOptions.ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles;
        opts.JsonSerializerOptions.DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
    });
builder.Services.AddEndpointsApiExplorer();

builder.Services.AddDbContext<ResumeDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("ResumeDb")));

builder.Services.AddScoped<IResumeRepository, ResumeRepository>();
builder.Services.AddScoped<IPdfGeneratorService, PdfGeneratorService>();

builder.Services.AddMassTransit(x =>
{
    x.AddConsumer<GrantResumeAccessConsumer>();
    x.UsingRabbitMq((context, cfg) =>
    {
        cfg.Host(builder.Configuration["RabbitMQ:Host"] ?? "localhost", h =>
        {
            h.Username(builder.Configuration["RabbitMQ:Username"] ?? "guest");
            h.Password(builder.Configuration["RabbitMQ:Password"] ?? "guest");
        });
        cfg.ReceiveEndpoint("grant-resume-access", e =>
        {
            e.ConfigureConsumer<GrantResumeAccessConsumer>(context);
        });
    });
});

// Load RSA public key from file (generated by IdentityService on first run)
var publicKeyPath = builder.Configuration["Jwt:PublicKeyPath"]
    ?? Path.Combine("..", "IdentityService", "keys", "public.pem");

RsaSecurityKey? rsaPublicKey = null;
if (File.Exists(publicKeyPath))
{
    var rsa = RSA.Create();
    rsa.ImportFromPem(File.ReadAllText(publicKeyPath));
    rsaPublicKey = new RsaSecurityKey(rsa);
}
else
{
    // Fallback: try to fetch from IdentityService HTTP endpoint
    try
    {
        using var http = new HttpClient { Timeout = TimeSpan.FromSeconds(5) };
        var resp = await http.GetFromJsonAsync<PublicKeyResponse>(
            builder.Configuration["IdentityService:PublicKeyUrl"] ?? "http://localhost:5001/auth/public-key");
        if (resp?.PublicKey != null)
        {
            var rsa = RSA.Create();
            rsa.ImportFromPem(resp.PublicKey);
            rsaPublicKey = new RsaSecurityKey(rsa);
        }
    }
    catch { /* will fail auth until key is available */ }
}

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidIssuer = builder.Configuration["Jwt:Issuer"] ?? "JobPortal",
            ValidateAudience = true,
            ValidAudience = builder.Configuration["Jwt:Audience"] ?? "JobPortalClients",
            ValidateLifetime = true,
            ValidateIssuerSigningKey = rsaPublicKey != null,
            IssuerSigningKey = rsaPublicKey,
            ClockSkew = TimeSpan.FromSeconds(30)
        };
    });

builder.Services.AddValidatorsFromAssemblyContaining<Program>();
builder.Services.AddFluentValidationAutoValidation();

builder.Services.Configure<ApiBehaviorOptions>(options =>
{
    options.InvalidModelStateResponseFactory = context =>
    {
        var err = context.ModelState.Values
            .SelectMany(v => v.Errors)
            .Select(e => e.ErrorMessage)
            .FirstOrDefault() ?? "Validation failed";
        return new BadRequestObjectResult(
            ResponseEnvelope<object>.Fail(err, context.HttpContext.TraceIdentifier));
    };
});

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "ResumeService API", Version = "v1" });
    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Enter 'Bearer {token}'",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer"
    });
    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
            },
            Array.Empty<string>()
        }
    });
    var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    if (File.Exists(xmlPath)) c.IncludeXmlComments(xmlPath);
});

var app = builder.Build();

app.UseSerilogRequestLogging();
app.UseMiddleware<ResumeService.Middleware.CorrelationIdMiddleware>();
app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "ResumeService API v1"));
app.UseMiddleware<GlobalExceptionMiddleware>();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

app.Run();

record PublicKeyResponse(string PublicKey);

public partial class Program { }
