using Elastic.Clients.Elasticsearch;
using Elastic.Transport;
using FluentValidation;
using FluentValidation.AspNetCore;
using JobCatalogService.Common;
using JobCatalogService.Data;
using JobCatalogService.Middleware;
using JobCatalogService.Repositories;
using JobCatalogService.Repositories.Interfaces;
using JobCatalogService.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using Serilog;
using System.Net.Http.Json;
using System.Security.Cryptography;

var builder = WebApplication.CreateBuilder(args);

builder.Host.UseSerilog((ctx, cfg) =>
{
    cfg.ReadFrom.Configuration(ctx.Configuration)
       .Enrich.FromLogContext()
       .WriteTo.Console(new Serilog.Formatting.Compact.CompactJsonFormatter())
       .WriteTo.File(new Serilog.Formatting.Compact.CompactJsonFormatter(),
           path: "logs/jobcatalog-.log",
           rollingInterval: RollingInterval.Day);
});

builder.Services.AddControllers()
    .AddJsonOptions(opts =>
    {
        opts.JsonSerializerOptions.ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles;
        opts.JsonSerializerOptions.DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
    });
builder.Services.AddEndpointsApiExplorer();

builder.Services.AddDbContext<JobDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("JobDb"),
        sql => sql.EnableRetryOnFailure(3)));

builder.Services.AddScoped<ICompanyRepository, CompanyRepository>();
builder.Services.AddScoped<IJobRepository, JobRepository>();

var esUri = builder.Configuration["Elasticsearch:Uri"] ?? "http://localhost:9200";
var esSettings = new ElasticsearchClientSettings(new Uri(esUri))
    .OnRequestCompleted(details =>
    {
        if (!details.HasSuccessfulStatusCode)
            Log.Warning("ES request failed [{Status}]: {Url} — {Error}",
                details.HttpStatusCode, details.Uri, details.OriginalException?.Message);
    });
builder.Services.AddSingleton(new ElasticsearchClient(esSettings));
builder.Services.AddScoped<IElasticsearchService, ElasticsearchService>();
builder.Services.AddHostedService<JobSyncService>();

// Load RSA public key from file (generated by IdentityService on first run)
var publicKeyPath = builder.Configuration["Jwt:PublicKeyPath"]
    ?? Path.Combine("..", "IdentityService", "keys", "public.pem");

RsaSecurityKey? rsaPublicKey = null;
if (File.Exists(publicKeyPath))
{
    var rsa = RSA.Create();
    rsa.ImportFromPem(File.ReadAllText(publicKeyPath));
    rsaPublicKey = new RsaSecurityKey(rsa);
}
else
{
    // Fallback: try to fetch from IdentityService HTTP endpoint
    try
    {
        using var http = new HttpClient { Timeout = TimeSpan.FromSeconds(5) };
        var resp = await http.GetFromJsonAsync<PublicKeyResponse>(
            builder.Configuration["IdentityService:PublicKeyUrl"] ?? "http://localhost:5001/auth/public-key");
        if (resp?.PublicKey != null)
        {
            var rsa = RSA.Create();
            rsa.ImportFromPem(resp.PublicKey);
            rsaPublicKey = new RsaSecurityKey(rsa);
        }
    }
    catch { /* will fail auth until key is available */ }
}

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidIssuer = builder.Configuration["Jwt:Issuer"] ?? "JobPortal",
            ValidateAudience = true,
            ValidAudience = builder.Configuration["Jwt:Audience"] ?? "JobPortalClients",
            ValidateLifetime = true,
            ValidateIssuerSigningKey = rsaPublicKey != null,
            IssuerSigningKey = rsaPublicKey,
            ClockSkew = TimeSpan.FromSeconds(30)
        };
    });

builder.Services.AddValidatorsFromAssemblyContaining<Program>();
builder.Services.AddFluentValidationAutoValidation();
builder.Services.Configure<ApiBehaviorOptions>(options =>
{
    options.InvalidModelStateResponseFactory = context =>
    {
        var firstError = context.ModelState.Values
            .SelectMany(v => v.Errors).Select(e => e.ErrorMessage).FirstOrDefault() ?? "Validation failed";
        return new BadRequestObjectResult(ResponseEnvelope<object>.Fail(firstError, context.HttpContext.TraceIdentifier));
    };
});

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "JobCatalogService API", Version = "v1" });
    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header. Enter 'Bearer {token}'",
        Name = "Authorization", In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey, Scheme = "Bearer"
    });
    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        { new OpenApiSecurityScheme { Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" } }, Array.Empty<string>() }
    });
    var xmlFile = $"{System.Reflection.Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    if (File.Exists(xmlPath)) c.IncludeXmlComments(xmlPath);
});

var app = builder.Build();

app.UseSerilogRequestLogging();
app.UseMiddleware<JobCatalogService.Middleware.CorrelationIdMiddleware>();
app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "JobCatalogService API v1"));
app.UseMiddleware<GlobalExceptionMiddleware>();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

app.Run();

record PublicKeyResponse(string PublicKey);

public partial class Program { }

